[package]
name = "samling"
version = "0.5.1"
license = "MIT"
edition = "2021"
description = "App for managing apparel collections"
repository = "https://github.com/hyperkliv/samling"
documentation = "https://docs.rs/samling/"
homepage = "https://github.com/hyperkliv/samling"

[dependencies]
argon2 = "0.5.0"
async-trait = "0.1.68"
axum = { version = "0.6.18", features = ["headers", "macros"] }
base64 = "0.21.0"
bytes = { version = "1.4.0", features = ["serde"] }
clap = { version = "4.2.7", features = ["derive", "env"], optional = true }
cornucopia_async = { version = "0.4.0", features = ["with-serde_json-1"] }
csv = "1.2.1"
deadpool-postgres = "0.10.5"
derive_more = "0.99.17"
dotenv = "0.15.0"
futures = "0.3.28"
governor = "0.5.1"
http = "0.2.9"
hyper = { version = "0.14.26", features = ["server", "tcp", "stream", "http1", "http2"] }
include_dir = "0.7.3"
indexmap = "1.9.3"
itertools = "0.10.5"
jsonwebtoken = "8.3.0"
log = "0.4.17"
mimalloc = { version = "0.1.37", default-features = false, optional = true }
mime = "0.3.17"
mime_guess = "2.0.4"
num_enum = "0.6.1"
once_cell = "1.17.1"
password-hash = { version = "0.5.0", features = ["std"] }
postgres-types = { version = "0.2.5", features = ["derive", "with-time-0_3", "with-serde_json-1"] }
rand = "0.8.5"
reqwest = { version = "0.11.17", features = ["rustls-tls", "json", "stream", "multipart"], default-features = false }
rust_decimal = { version = "1.29.1", features = ["db-tokio-postgres", "db-postgres", "serde-with-float"] }
rust_xlsxwriter = "0.38.0"
schemars = { version = "0.8.12", features = ["derive", "preserve_order", "bytes", "url", "rust_decimal"] }
sentry = { version = "0.31.0", default-features = false, features = ["rustls", "tracing", "backtrace", "contexts", "panic", "tokio", "reqwest", "tower"] }
serde = { version = "1.0.162", features = ["derive"] }
serde_json = { version = "1.0.96", features = ["preserve_order"] }
serde_path_to_error = "0.1.11"
slug = "0.1.4"
smol_str = { version = "0.2.0", features = ["serde"] }
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.40"
# TODO: Remove `serde-well-known`, it's being deprecated. See this commit:
#       https://github.com/time-rs/time/commit/110e17bb8461816551f7197a2aa2e34c981fa22d
time = { version = "0.3.21", features = ["serde", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.28.0", default-features = false, features = ["signal", "macros", "rt-multi-thread"] }
tokio-postgres = "0.7.8"
tower = "0.4.13"
tower-http = { version = "0.4.0", default-features = false, features = ["fs", "trace", "cors", "compression-full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", optional = true }
url = { version = "2.3.1", features = ["serde"] }

[features]
default = ["cli"]
cli = ["clap", "tracing-subscriber"]
ui = []
