[package]
name = "samling"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.4.1"
async-trait = "0.1.60"
axum = { version = "0.6.1", features = ["headers", "macros"] }
base64 = "0.20.0"
bytes = { version = "1.3.0", features = ["serde"] }
clap = { version = "4.0.32", features = ["derive", "env"], optional = true }
cornucopia_async = { version = "0.4.0", features = ["with-serde_json-1"] }
csv = "1.1.6"
deadpool-postgres = "0.10.3"
derive_more = "0.99.17"
dotenv = "0.15.0"
futures = "0.3.25"
governor = "0.5.1"
http = "0.2.8"
hyper = { version = "0.14.23", features = ["server", "tcp", "stream", "http1", "http2"] }
include_dir = "0.7.3"
indexmap = "1.9.2"
itertools = "0.10.5"
jsonwebtoken = "8.2.0"
log = "0.4.17"
mime = "0.3.16"
mime_guess = "2.0.4"
num_enum = "0.5.7"
once_cell = "1.17.0"
password-hash = { version = "0.4.2", features = ["std"] }
postgres-types = { version = "0.2.4", features = ["derive", "with-time-0_3", "with-serde_json-1"] }
rand = "0.8.5"
reqwest = { version = "0.11.13", features = ["rustls-tls", "json", "stream", "multipart"], default-features = false }
rust_decimal = { version = "1.27.0", features = ["db-tokio-postgres", "db-postgres", "serde-with-float"] }
rust_xlsxwriter = "0.19.0"
schemars = { version = "0.8.11", features = ["derive", "preserve_order", "bytes", "url", "rust_decimal"] }
sentry = { version = "0.29.1", default-features = false, features = ["rustls", "tracing", "backtrace", "contexts", "panic", "tokio", "reqwest", "tower"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
serde_path_to_error = "0.1.9"
slug = "0.1.4"
smol_str = "0.1.23"
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.38"
# TODO: Remove `serde-well-known`, it's being deprecated. See this commit:
#       https://github.com/time-rs/time/commit/110e17bb8461816551f7197a2aa2e34c981fa22d
time = { version = "0.3.17", features = ["serde", "serde-human-readable", "serde-well-known"] }
tokio = { version = "1.23.0", features = ["full"] }
tokio-postgres = "0.7.7"
tower = "0.4.13"
tower-http = { version = "0.3.5", default-features = false, features = ["fs", "trace", "cors", "compression-full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", optional = true }
url = { version = "2.3.1", features = ["serde"] }

[features]
default = ["cli"]
cli = ["clap", "tracing-subscriber"]
ui = []
