apiVersion: v1
kind: Service
metadata:
  name: samling
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
