name: New production version

on:
  push:
    tags:
      - "samling-v*"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify hyperkliv/www-samling-io
        uses: peter-evans/repository-dispatch@v3
        with:
          # https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          # NOTE: The custom github token is important, as repository_dispatch won't work across repos otherwise
          token: ${{ secrets.TRIGGERING_GITHUB_TOKEN }}
          repository: hyperkliv/www-samling-io
          event-type: new-production-samling-docker-image
          client-payload: '{"sha": "${{ github.sha }}"}'
